name: 04- Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setting Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
              working-directory: 04-Using-Actions/react-app
            - name: Printing Folders
              run: ls
              



#0. Checkout the code from the repository
#1. Install deps of our react application
#2. Execute automated tests